- hosts: website
  tasks:
    - name: enable overcommit_memory
      shell: sysctl vm.overcommit_memory=1
    - name: patch sysctl.conf
      patch: src=sysctl.patch dest=/etc/sysctl.conf
    - name: add redis-server repository
      apt_repository: repo='ppa:chris-lea/redis-server' state=present
    - name: install redis-server
      apt: name=redis-server update_cache=yes
    - name: get newest version of repository
      git: repo=https://github.com/justuswilhelm/portfolio.git
        dest=/root/portfolio
        clone=yes
    - name: restart server
      supervisorctl: state=restarted
        config=/root/portfolio/supervisord.conf
        name='app:'
