- hosts: website
  tasks:
    - name: get newest version of repository
      git: repo=https://github.com/justuswilhelm/portfolio.git
        dest=/root/portfolio
        clone=yes
    - name: restart server
      supervisorctl: state=restarted
        config=/root/portfolio/supervisord.conf
        name='app:'
